### ISSUE TITLE
webowl

### ISSUE THREAD

**Issue by mohamedmhe** [pipauwel/IFCtoRDF#18]
why i can't see the graph on http://www.visualdataweb.de/webvowl/#url=https://standards.buildingsmart.org/IFC/DEV/IFC4_1/OWL/ontology.json ?

**Comment by akuckartz** [comment]
Why is the file named ontology.json and not ontology.jsonld as the JSON-LD specification suggests?

**Comment by pipauwel** [comment]
> why i can't see the graph on http://www.visualdataweb.de/webvowl/#url=https://standards.buildingsmart.org/IFC/DEV/IFC4_1/OWL/ontology.json ?

Thank you for testing. That is a very good question, and I am afraid I don't know why that particular file does not load in WebVOWL. The tool seems to be stuck on the visualisation part. Maybe you can ask the tool creators to test this with that JSON version of the ontology?

The IFC ontology does load in WebVOWL when you use the IRI of the ontology: https://standards.buildingsmart.org/IFC/DEV/IFC4/ADD2/OWL/. That also seems to be a better approach, considering that this is the identifier of the ontology?

**Comment by pipauwel** [comment]
> Why is the file named ontology.json and not ontology.jsonld as the JSON-LD specification suggests?

It was generated as such by the WIDOCO tool that I used to generate the documentation. I could use the alternative file name extension instead. Does it cause you any particular problem?

**Comment by akuckartz** [comment]
The only problem I am *aware* of is that the file extension is not the one specified in the W3C Recommendation - but there might be connection with the current issue ;-)

**Comment by akuckartz** [comment]
Maybe the Web Server uses the JSON Media Type for the .json file instead of the JSON-LD Media Type?

**Comment by pipauwel** [comment]
I am sorry for this very late reply. Anyhow, I have looked into this problem again.

I notice that this works:
http://www.visualdataweb.de/webvowl/#iri=https://standards.buildingsmart.org/IFC/DEV/IFC4_1/OWL#
So I would recommend to use that approach: instead of referring to the JSON-LD, use the actual URI of the ontology instead.

Further explanation:
I tried to make WebVOWL work with the JSON file, but I did not manage. I downloaded the JSON file and uploaded it in WebVOWL, but it never managed. The WebVOWL error indicated that the uploaded file is not a valid ontology, and I was recommended to validate it using the OWLAPI Validator from org.semanticweb.owlapi.io (http://visualdataweb.de/validator/validate). This validator indicates that it tried to parse the JSON file with the following parsers and failed:

1. RDFXMLParser
2. OWLXMLParser
3. OWLFunctionalSyntaxOWLParser
4. TurtleOntologyParser
5. OWLOBOParser
6. KRSS2OWLParser
7. ManchesterOWLSyntaxOntologyParser

This appears to not include a JSONLD syntax anyhow, regardless of file name extension, so it makes sense that it fails. I suspect that WebVOWL is thus simply not compatible with JSON-LD. In that case, this issue belongs to the WebVOWL software rather than to this IFCtoRDF repo.

@akuckartz, are you able to load other JSON-LD files in WebVOWL?
