### ISSUE TITLE
how to convert ifc file to rdf file

### ISSUE THREAD

**Issue by Katherine-HYT** [pipauwel/IFCtoRDF#23]
I opened the project in eclipse, but I don't know how to use it. Could you explain to me please? It is the first time, so something I cannot understand.

**Comment by pipauwel** [comment]
I am sorry for a late reply. I tried to give pointers in the [README.md] file / homepage of this repository, so please read that. In short, there are two options:

1. You don't want to edit the code
- download the executable shaded-jar from the releases page: 
https://github.com/pipauwel/IFCtoRDF/releases/download/IFCtoRDF-0.4/IFCtoRDF-0.4-shaded.jar
- open a command line interface (console, command prompt, other) and execute the following command: ``java -jar IFCtoRDF-0.4-shaded.jar <input-file.ifc> <output-file.ttl>``
- find the resulting file or file an issue in this repo

2. You want to edit the code
- fork and/or download the code from GitHub
- make sure to have a recent java JDK and maven installed
- load the maven project into your favorite editor (Eclipse, IntelliJ, other)
- compile the project with ``mvn compile`` in order to download all dependencies and get started
- execute the code with the command ``be.ugent.IfcSpfReader --baseURI http://www.testuri.be/ inputfile.ifc outputfile.ttl``

**Comment by Katherine-HYT** [comment]
Thank you very much!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pipauwel/IFCtoRDF"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月30日(星期天) 凌晨4:24
收件人:&nbsp;"pipauwel/IFCtoRDF"<IFCtoRDF@noreply.github.com&gt;;
抄送:&nbsp;"Katherine"<945774816@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pipauwel/IFCtoRDF] how to convert ifc file to rdf file (#23)





 
I am sorry for a late reply. I tried to give pointers in the [README.md] file / homepage of this repository, so please read that. In short, there are two options:
  
You don't want to edit the code
   
download the executable shaded-jar from the releases page:
 https://github.com/pipauwel/IFCtoRDF/releases/download/IFCtoRDF-0.4/IFCtoRDF-0.4-shaded.jar
 
open a command line interface (console, command prompt, other) and execute the following command: java -jar IFCtoRDF-0.4-shaded.jar <input-file.ifc&gt; <output-file.ttl&gt;
 
find the resulting file or file an issue in this repo
   
You want to edit the code
   
fork and/or download the code from GitHub
 
make sure to have a recent java JDK and maven installed
 
load the maven project into your favorite editor (Eclipse, IntelliJ, other)
 
compile the project with mvn compile in order to download all dependencies and get started
 
execute the code with the command be.ugent.IfcSpfReader --baseURI http://www.testuri.be/ inputfile.ifc outputfile.ttl
