### ISSUE TITLE
On deduplicating property values 

### ISSUE THREAD

**Issue by fkleedorfer** [pipauwel/IFCtoRDF#37]
The RdfWriter keeps a map of all property/type/value combinations and if a combination re-occurs, the resource generated to represent that property is linked to again, instead of generating another couple of triples to represent the re-occurrence.

This saves space, but if I am not mistaken, this approach is only correct for read-only models. As soon as we start modifying values, we risk inadvertedly changing all values - so for read/write models, this should be disabled.

Also, not deduplicating property values as stated above does not affect the correctness of the resulting model.

Right?

**Comment by pipauwel** [comment]
If my memory does not abandon me here, this had been implemented using the --removeDuplicates flag / removeDuplicates option: https://github.com/pipauwel/IFCtoRDF/blob/3a884abb41420a47be80b38141e277a9dcb25993/src/main/java/be/ugent/IfcSpfReader.java#L54.

I thought that this was by default disabled, and output is thus by default simply generated as 'another couple of triples to represent the re-occurrence'. This is indeed preferred, because this would indeed avoid that, when somebody modifies the value, it is not modified for all references to that line. 

Note that this code assumes IFC, which is by default read-only. I would not encourage modifying the content of the IFC, either in SPF or RDF, except if you really know what you are doing and it is small-scale. It requires a different software setup, imo.

**Comment by fkleedorfer** [comment]
Thanks!

Actually, `removeDuplicates` governs another deduplication behaviour: apparently, some IFC files contain exactly identical lines, except for the object number (or whatever the leading number is called). if `removeDuplicates == true` , all of those are replaced by the IFCVO generated for the first such line. I am not sure how important this behaviour is, but it seems to have solved some kind of problem.

I actually asked the question initially because omitting both deduplication  behaviours speeds up the conversion process a lot, and I just want to be sure it's not in any way required for correctness to do it.

**Comment by pipauwel** [comment]
These line numbers are internal object identifiers that are known and used inside the SPF file only (so I would always try to abandon them asap). If the rest of the line is identical, then the object has the same content (CartesianPoint X == CartesianPoint Y). So it is fine to simply use the same object (one instead of two - de-duplication). Yet, indeed, if one of those changes, one needs to be aware that it affects all occurrences. So therefore I backtracked and found it safer to keep them duplicate and just keep it as it comes in in the SPF file. 

You seem to be talking about property values and duplicates there. If I am reading you correctly, keeping duplicates:
- speeds up conversion time
- keeps correct content
- is safer if one makes edits
- and there are no drawbacks (?) 

In that case, it seems reasonable to maintain the duplicates during conversion. Do you see difference in the output?

**Comment by fkleedorfer** [comment]
Yes, the output file, of course, is bigger. other than that, none that I know of.
